backend:
  name: github
  repo: akkey247/hugo-site-test
  branch: master
  base_url: https://crimson-morning-feff.akkey52417.workers.dev/
  auth_endpoint: auth

site_url: https://akkey247.github.io/hugo-site-test
display_url: https://akkey247.github.io/hugo-site-test

media_folder: static/images
public_folder: /hugo-site-test/images

collections:
  - name: posts
    label: 記事
    folder: content/posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: md
    format: yaml-frontmatter
    fields:
      - { label: タイトル, name: title, widget: string }
      - { label: 公開日, name: date, widget: datetime }
      - { label: 下書き, name: draft, widget: boolean, default: true }
      - { label: 本文, name: body, widget: markdown }